name: placar_iterativo_app
description: "Aplicativo de placar esportivo interativo para Android e Windows."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  flutter_emoji: ^2.5.1
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.2.1
  
  # State Management
  flutter_modular: ^6.3.4
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Media
  image_picker: ^1.0.7
  file_picker: ^10.1.9
  
  # Audio
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # Removendo a seção de fontes personalizadas, pois estamos usando o google_fonts
  # que carrega as fontes diretamente da web
